### PR TITLE
[WIP] Behavior Tree rework

### PR DESCRIPTION
**Pull request by dkambersky**
Accompanies [the main PR](https://github.com/MovingBlocks/Terasology/pull/2992).

### CODE REVIEW

**Comment by flo** [comment]
@dkambersky where have the behaviors been moved to?

**Comment by dkambersky** [comment]
@flo [Behaviors](https://github.com/Terasology/Behaviors/tree/behaviorv2), mostly. some of the WildAnimals related Actions/behaviors are now in WildAnimals, but I'll probably move a significant chunk of that before the final merge.

**Comment by flo** [comment]
@dkambersky so will prefabs based on AdvancedBehaviors work? e.g. have you adjusted that module also accordingly? Or is that module now broken?

**Comment by dkambersky** [comment]
As with Behaviors, Pathfinding, and the main project, everything related to the new BT framework lives on its own branch in its respective repository.

I've rewritten the WildAnimals prefabs based on AdvancedBehaviors to be used in the new system, check out https://github.com/Terasology/WildAnimals/pull/21. They still need a few tweaks but they're mostly working.

Maybe ask me on slack if you need details? so we don't clog up this merged PR.

**Pull request merged**
