### PR TITLE
Add PathFinder for Dijkstra and A-Star algorithms

### PR DESCRIPTION
**Pull request by msteiger**
This PR adds path-finding support. It ..
* supports Dijkstra's algorithm, A-Star (A*) and Best-First Search
* clean implementation (at least I tried my best)
* documented
* very flexible (vertex is a generic parameter, edge is a simple 3 method interface)
* non-viral OSS license (Apache 2)
* can be used with modern Java8 features
* comes with unit tests

Kudos go to AmitP for the very well written [Introduction to A*](http://theory.stanford.edu/~amitp/GameProgramming/AStarComparison.html).
A demonstration video of Dijkstra and A* can be watched here: https://youtu.be/Te7aqQCPSX0

In contrast to the existing A-Star implementation this works on general graphs (hence the name).

### CODE REVIEW

**Comment by Cervator** [comment]
@synopia where aaaaaaaare yoooooouuuu? :-)

I'm still amazed that's a video in WorldViewer. How? Very nicely done :D

**Comment by msteiger** [comment]
I'd like to proceed with this soon (if possible) as Cities' new road planning system depends on it.

**Comment by Cervator** [comment]
I caught @synopia on IRC and he said he'd try to catch you online. You could just merge this and discuss further later though - just new files anyway :-)

**Comment by Cervator** [comment]
Annnd merging this without further ado.

**Pull request merged**
